"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[git]
sign-on-push = true

[signing]
backend = "gpg"
behavior = "own"

[ui]
default-command = "log"

[user]
email = "hunarroopcodes@gmail.com"
name = "Hunar Roop Kahlon"
